- name: Install prerequisites
  become: yes
  apt:
    pkg:
      - python3-setuptools
      - python3-pip

- name: Install locales
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8


- name: Install locales for root user
  become: yes
  locale_gen: name={{ item }} state=present
  with_items:
    - en_US.UTF-8
