version: "3"

services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=vantage"
      - "PGDATA=/data"
    ports:
      - 5433:5432
    volumes:
      - ./pgdata:/scratch/pgdata
