---
# tasks file for docker
- name: Install prerequisites for using apt update_cache
  become: yes
  apt:
    pkg:
      - apt-transport-https
      - python3-apt
      - aptitude
- name: Install prerequisites for docker
  become: yes
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

- name: Add key from docker
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  become: yes
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install docker CE
  become: yes
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Install docker python library and prerequisites
  pip:
    name:
      - docker
      - requests
      - docker-compose
- name: install docker compose
  become: yes
  shell:
    cmd: curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Change permissions docker compose
  become: yes
  file:
    path: /usr/local/bin/docker-compose
    mode: u=x

- name: Create symbolic link docker compose
  become: yes
  file:
    state: link
    src: /usr/local/bin/docker-compose
    dest: /usr/bin/docker-compose
