- name: Mount scratch disk
  hosts:
    - harbor-registries
  roles:
    - docker
  become: yes
  vars:
    scratch_device: "/dev/vdb"
    scratch_fstype: "ext4"
    scratch_mount_point: "/mnt/scratch"
    harbor_version: "v2.1.3"
    app_dir: "/app"
    certificate_path: "/etc/letsencrypt/live/{{inventory_hostname}}/fullchain.pem"
    private_key_path: "/etc/letsencrypt/live/{{inventory_hostname}}/privkey.pem"

  # TODO: Formatting and mounting the scratch disk should be a role
  tasks:
    - name: Format scratch disk
      filesystem:
        dev: "{{scratch_device}}"
        fstype: "{{scratch_fstype}}"

    - name: Create scratch mount point
      file:
        state: "directory"
        path: "{{scratch_mount_point}}"

    - name: Mount scratch disk
      mount:
        fstype: "{{scratch_fstype}}"
        path: "{{scratch_mount_point}}"
        src: "{{scratch_device}}"
        state: "mounted"
    - name: Create app dir
      file:
        state: "directory"
        path: "{{app_dir}}"

    - name: Download harbor
      get_url:
        url: >
          https://github.com/goharbor/harbor/releases/download/{{harbor_version}}/harbor-online-installer-{{harbor_version}}.tgz
        dest: "{{app_dir}}/harbor_installer.tgz"

      # TODO: Verify file

    - name: Unpack installer
      unarchive:
        dest: "{{app_dir}}"
        remote_src: yes
        src: "{{app_dir}}/harbor_installer.tgz"

    - name: Copy harbor config to harbor dir
      template:
        src: files/harbor/harbor.yml
        dest: "{{app_dir}}/harbor/harbor.yml"
    # TODO: Following task will fail because there is not a CA certificate. For now the CA certificate needs to be
    #       installed manually. See https://certbot.eff.org/lets-encrypt/ubuntubionic-other
    - name: Install harbor
      shell:
        chdir: "{{app_dir}}/harbor"
        cmd: "./install.sh"

